### ISSUE TITLE
undefined method 'ip_id'

### ISSUE THREAD

**Issue by eidermar** [matthutchinson/lifx_dash#5]
hi matt

ran into some troubles with my dashes. lifx_dash randomly crashes after the most recent changes with the following message:

error: undefined method 'ip_id' for nil:NilClasserror: undefined method 'ip_id' for nil:NilClass

any clue what's wrong on my side?

thanks for your help!

**Comment by matthutchinson** [comment]
Can you paste the full error here, and let me know what gem version you are using.  I thought I had patched this bug.  This conditional should check for any `nil` on `pkt`; https://github.com/matthutchinson/lifx_dash/blob/master/lib/lifx_dash/capturer.rb#L26

**Comment by eidermar** [comment]
gem list output: lifx_dash (0.2.3, 0.2.2, 0.1.3)

that's the full error message as shown in lifx_dash.log

let me know if there's anything else I can provide. 

btw running lifx_dash on Ubuntu 16.4 LTS

**Comment by matthutchinson** [comment]
can you try uninstalling the older versions? leaving only 0.2.3

**Comment by eidermar** [comment]
ok, I uninstalled the old gems and so far no crashes. I'll monitor going forward and will report back.

**Comment by eidermar** [comment]
matt, thanks a lot for helping out. It seems the problems are gone since removing the old gems. I think it's save to close the issue.

**Comment by matthutchinson** [comment]
👍🏼
